version: "2"

run:
  concurrency: 4
  timeout: 5m
  tests: false
  build-tags:
    - mytag

output:
  formats:
    text:
      print-linter-name: true
      print-issued-lines: true

linters:
  default: none
  enable:
    - bodyclose
    - dupl
    - errcheck
    - gocognit
    - goconst
    - gosec
    - govet
    - ineffassign
    - lll
    - misspell
    - revive
    - staticcheck
    - unused
    - copyloopvar
    - intrange
    - nilerr
    - errorlint

  settings:
    dupl:
      threshold: 200
    errcheck:
      check-type-assertions: false
      check-blank: false
    exhaustive:
      default-signifies-exhaustive: false
    gocognit:
      min-complexity: 35
    goconst:
      min-len: 3
      min-occurrences: 3
    govet:
      enable-all: false
      enable:
        - atomicalign
      disable:
        - shadow
      settings:
        printf:
          funcs:
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
            - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf
    gosec:
      excludes:
        - G301
        - G304
    lll:
      line-length: 160
      tab-width: 4
    misspell:
      locale: US
    nestif:
      min-complexity: 4
    revive:
      rules:
        - name: exported
          disabled: true

  exclusions:
    generated: lax
    presets:
      - comments
    paths:
      - src/external_libs
      - autogenerated_by_my_lib
      - config
      - pkg
      - "^_.*"
    rules:
      - path: _test\.go
        linters:
          - errcheck
          - dupl
          - gosec
          - lll
      - path: html_.*\.go
        linters:
          - lll
      - path: model/.*\.go
        linters:
          - lll
      - linters:
          - gosec
        text: "G402"
      - linters:
          - gosec
        text: "G501"
      - linters:
          - gosec
        text: "G404"
      - linters:
          - gosec
        text: "G401"
      - linters:
          - gosec
        text: "G505"
      - linters:
          - staticcheck
        text: "SA9003:"
      - linters:
          - lll
        source: "^//go:generate "

formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: lax
    paths:
      - src/external_libs
      - autogenerated_by_my_lib

severity:
  default: error
  rules:
    - linters:
        - dupl
      severity: info
